### ISSUE TITLE
Missing Drivers

### ISSUE THREAD

**Issue by wengland02** [64Soft/NRatings.Client#35]
A few drivers made one off starts in the Truck race at Bristol Dirt but their names aren't coming up in the program for the ratings for the race. These drivers include Chase Elliott, Mike Marlar, and Buddy Kofoid. All drivers that have made previous starts this year have ratings for the race but not the one offs.

**Comment by ai-line-mod** [comment]
Hi - sorry it's taken so long to get back to you. Are you sure any drivers at all are appearing for the Bristol dirt race? When I try to select ratings for that race only I see no drivers. Can you verify?

**Comment by wengland02** [comment]
After testing it again, I can confirm that the ratings for the Bristol dirt race do not work no matter the driver. Also, no ratings are available for any truck races after the Bristol dirt race.

**Comment by 64Soft** [comment]
@ai-line-mod yes I quickly ran a debug yesterday and indeed saw some issues on the Truck and ARCA series data processing for recent races. I hope to be able to look into it somewhere later this week.

**Comment by 64Soft** [comment]
Trucks are ok now. Was an issue with driver Michael Kofoid being renamed to Buddy Kofoid on Racing-Reference.info and that screwed things up during parsing. ARCA is ok too because it halted parsing after the truck series error. However the ARCA East, West, Whelen Modified and Pinty's series is still giving another error that needs further investigation
