### ISSUE TITLE
how do you make an account

### ISSUE THREAD

**Issue by kadenmkw** [64Soft/NRatings.Client#44]
Sorry I know this isnt a code issue but I can't make an account and was wondering how I could

**Comment by kadenmkw** [comment]
![Screenshot (240)](https://user-images.githubusercontent.com/68365304/220228465-2827ea02-0dd7-41f4-9112-076cd2febabe.png)

**Comment by ai-line-mod** [comment]
Make sure windows has a default browser (eg firefox, edge). To do that, open the start menu and type default apps. Open that and be sure you have a browser for Web Browser.

**Comment by 64Soft** [comment]
@ai-line-mod is correct, the login process needs to use your default browser. Have you been able to solve it ?

**Comment by wobert6969** [comment]
I have the same issue and I tried the default browser thing but it still shows same error message.

**Comment by ai-line-mod** [comment]
@64soft From reddit:

"Alright so I downloaded Chrome and made it my default browser. I opened up NRatings, hit tools->options, and then hit log in. This time it let me log in and enter my email and password and stuff. Which I did and it said log in completed. But when I went back into NRatings the same error message appeared."

A default browser is set, it allows a login, but for some reason the credentials aren't being passed back to the client? I have not been able to replicate this myself, nor am I certain where the exact issue could lie.

**Comment by ai-line-mod** [comment]
Try a different default browser. To change it: https://support.microsoft.com/en-us/windows/change-your-default-browser-in-windows-020c58c6-7d77-797a-b74e-8f07946c5db6

**Comment by ai-line-mod** [comment]
@64Soft From reddit:

Ok so, today I went to a place where I was on a good wifi signal again. So I deleted NRatings, and I uninstalled Google Chrome. Then I redownloaded NRatings and installed Chrome. So per usual I set Chrome as my default browser and opened NRatings. I went to log in and it took me to the page saying log in completed like usual. EXCEPT this time it actually logged me in. Now here is what I think the fix was: Simply redownloading NRatings, and using Chrome for the 64soft authentication process. The reason I think this is because when I was on good wifi last weekend I tried it with Mircosoft Edge as the default browser and it didn't work despite me redownloading NRatings a couple times. This week when I tried using chrome I was on a 1 bar phone hotspot which is why it probably didn't work. Anyways I got all my ratings for my mods updated to irl data and thought I'd share this with you,. Thank you for your help good sir."

I'm guessing it's an issue with poor wifi/hotspot. Pasting here as I think this is useful information.
